/*

 PADDLE1.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char paddle1[] =
{
  0xFF,0xFF,0x80,0xFF,0xBF,0xC0,0xA0,0xC0,
  0xA0,0xC0,0xBF,0xC0,0x80,0xFF,0xFF,0xFF
};

/* End of PADDLE1.C */
